version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: chattingo-mysql-db
    environment:
      MYSQL_DATABASE: chattingo
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
        image: ergaurav3155/chattingo-backend:${BUILD_NUMBER}    container_name: chattingo-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/chattingo
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - JWT_SECRET=cl+YzgqzeDUWlL/G8jLLtvaRD6UiR1+VSi6yJInHAzEPisfBeSu1XebQIIkWnub8JOICKk763S0mOs1l3Uc2YQ==
    depends_on:
      db:
        condition: service_healthy

  frontend:
    image: ergaurav3155/chattingo-frontend:${BUILD_NUMBER}
    container_name: chattingo-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mysql_data:
